In [16]:
import numpy as np
import pandas as pd

weights = 0
bias = 0

def fit (features, target):
    pass

target = np.array([[22],[33],[45]])
print(target)
        
data = {'Age': [18, 21, 33],
        'Price': [5000, 6000, 8000],
       'Bitches': [10, 9, 5],
       'Country': [1,3,7]}
        
X = pd.DataFrame.from_dict(data)
print (X.shape)

newarr = np.ones([X.shape[0],1])
print(newarr)

colided = np.hstack([newarr, X.values])
print(colided)



[[22]
 [33]
 [45]]
(3, 4)
[[1.]
 [1.]
 [1.]]
[[1.0e+00 1.8e+01 5.0e+03 1.0e+01 1.0e+00]
 [1.0e+00 2.1e+01 6.0e+03 9.0e+00 3.0e+00]
 [1.0e+00 3.3e+01 8.0e+03 5.0e+00 7.0e+00]]


In [7]:
X

Age  Price  Bitches  Country
0   18   5000       10        1
1   21   6000        9        3
2   33   8000        5        7

In [19]:
weights = np.linalg.inv(colided.T@colided)@colided.T@target
weights

array([[-2.27275000e+03],
       [-4.47750000e+02],
       [ 1.71484375e+00],
       [ 5.37000000e+02],
       [ 1.67000000e+02]])

In [20]:
prediction = colided@weights
prediction

array([[3778.96875],
       [3947.5625 ],
       [ 524.25   ]])